<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'console.command.cache_pool_list' shared service.

$this->privates['console.command.cache_pool_list'] = $instance = new \Symfony\Bundle\FrameworkBundle\Command\CachePoolListCommand([0 => 'cache.app', 1 => 'cache.system', 2 => 'cache.validator', 3 => 'cache.serializer', 4 => 'cache.annotations', 5 => 'cache.property_info', 6 => 'array', 7 => 'cache.security_expression_language', 8 => 'cache.doctrine.orm.default.result', 9 => 'cache.doctrine.orm.default.query', 10 => 'api_platform.cache.route_name_resolver', 11 => 'api_platform.cache.metadata.resource', 12 => 'api_platform.cache.metadata.resource.legacy', 13 => 'api_platform.cache.metadata.property.legacy', 14 => 'api_platform.cache.subresource_operation_factory', 15 => 'api_platform.cache.metadata.property', 16 => 'api_platform.cache.metadata.resource_collection', 17 => 'api_platform.cache.identifiers_extractor', 18 => 'prestashop.static_cache.adapter']);

$instance->setName('cache:pool:list');

return $instance;
