<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'PrestaShop\PrestaShop\Core\Security\TokenAuthenticator' shared service.

return $this->privates['PrestaShop\\PrestaShop\\Core\\Security\\TokenAuthenticator'] = new \PrestaShop\PrestaShop\Core\Security\TokenAuthenticator(new \PrestaShopBundle\Security\OAuth2\ResourceServer(new \League\OAuth2\Server\ResourceServer(($this->privates['PrestaShopBundle\\Security\\OAuth2\\Repository\\AccessTokenRepository'] ?? ($this->privates['PrestaShopBundle\\Security\\OAuth2\\Repository\\AccessTokenRepository'] = new \PrestaShopBundle\Security\OAuth2\Repository\AccessTokenRepository())), new \League\OAuth2\Server\CryptKey('-----BEGIN PUBLIC KEY-----'."\n".'MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAizgWAWYGqwFGQ4SLeYg5'."\n".'MzXE/83jejYhha44fNBTl/sWrf6f9s2LKeYtBq0PuFXAebo3LroVXa6kF3sFhZfL'."\n".'jmjrII/0qTtI+rOZ5Hm1LpB5paNiQ+KmkEZNI5GSmcn9YlhWXBPJ6q8yIOPFAGj7'."\n".'UV4lA3yYa0GNVfPy3Xbri2/hrmPsTZ85Qq/eCDI6itEd/hDBL3c23rGNouoIWn4k'."\n".'fEiBHtxDQ4x+5kCYYXFQbEMlfUyG8lpUl//xtYM7EbrJRTc5y3iCDkvD10xAU4d9'."\n".'kYL8zggf3X9unIHbO+l4zI5zteedhdnj+DkrXcHFCE9XTO9Tmxnleoev4dtaHvXd'."\n".'VQIDAQAB'."\n".'-----END PUBLIC KEY-----'."\n".'')), ($this->privates['security.user.provider.concrete.oauth2'] ?? ($this->privates['security.user.provider.concrete.oauth2'] = new \Symfony\Component\Security\Core\User\InMemoryUserProvider([])))), ($this->privates['Symfony\\Bridge\\PsrHttpMessage\\Factory\\PsrHttpFactory'] ?? $this->load('getPsrHttpFactoryService.php')));
