<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerEh6I5Tk\appAppKernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerEh6I5Tk/appAppKernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerEh6I5Tk.legacy');

    return;
}

if (!\class_exists(appAppKernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerEh6I5Tk\appAppKernelDevDebugContainer::class, appAppKernelDevDebugContainer::class, false);
}

return new \ContainerEh6I5Tk\appAppKernelDevDebugContainer([
    'container.build_hash' => 'Eh6I5Tk',
    'container.build_id' => '851d0a9d',
    'container.build_time' => 1707822421,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerEh6I5Tk');
