<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerMxlaezu\appAppKernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerMxlaezu/appAppKernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerMxlaezu.legacy');

    return;
}

if (!\class_exists(appAppKernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerMxlaezu\appAppKernelDevDebugContainer::class, appAppKernelDevDebugContainer::class, false);
}

return new \ContainerMxlaezu\appAppKernelDevDebugContainer([
    'container.build_hash' => 'Mxlaezu',
    'container.build_id' => 'd3758ade',
    'container.build_time' => 1708960521,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerMxlaezu');
